import "./globals.css";

import type { Metadata } from "next";
import { Inter_Tight, Space_Grotesk } from "next/font/google";
import { Providers } from "@/components/Providers";
import { Navbar } from "./(landingPage)/_components/Navbar";
import { Footer } from "./(landingPage)/_components/Footer";

const inter = Inter_Tight({
  weight: "variable",
  variable: "--font-inter",
  subsets: ["latin"],
});
const space_grotesk = Space_Grotesk({
  weight: "variable",
  variable: "--font-space_grotesk",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${space_grotesk.variable} bg-white`}>
        <Providers>
          <div className="min-h-screen flex flex-col">
            <Navbar />
            <div className="flex-1">{children}</div>
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
